-- MySQL Script generated by MySQL Workbench
-- Ср 08 авг 2018 05:09:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema CityAndCountry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CityAndCountry` ;
USE `CityAndCountry` ;

-- -----------------------------------------------------
-- Table `CityAndCountry`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CityAndCountry`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Country_Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Country_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CityAndCountry`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CityAndCountry`.`Region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Region_Name` VARCHAR(100) NULL,
  `Country_id` INT NOT NULL,
  `Region_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Region_Country_idx` (`Country_id` ASC),
  INDEX `fk_Region_Region1_idx` (`Region_id` ASC),
  CONSTRAINT `fk_Region_Country`
    FOREIGN KEY (`Country_id`)
    REFERENCES `CityAndCountry`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Region_Region1`
    FOREIGN KEY (`Region_id`)
    REFERENCES `CityAndCountry`.`Region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CityAndCountry`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CityAndCountry`.`City` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `City_Name` VARCHAR(45) NULL,
  `Region_id` INT NULL,
  `Country_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_City_Region1_idx` (`Region_id` ASC),
  INDEX `fk_City_Country1_idx` (`Country_id` ASC),
  CONSTRAINT `fk_City_Region1`
    FOREIGN KEY (`Region_id`)
    REFERENCES `CityAndCountry`.`Region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`Country_id`)
    REFERENCES `CityAndCountry`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
